pkgname="dotfiles-installer"
pkgver="1.0.0"
pkgdesc="Jayfaza's dotfiles installer"
arch=("x86_64")
depens=("python", "python-pip", "git")
license=("custom")
source=("app.py")
source=("config.py")
source=("executor.py")
source=("installer.py")
source=("printer.py")
source=("system_manager.py")
source=("command.py")
source=("config_stower.py")
source=("garbage_cleaner.py")
source=("main.py")
source=("parser.py")
source=("tweaker.py")
sha512sums=("SKIP")
